let cards: Map<string, string> = new Map(
    [
        [ "c01", "/src/assets/img/cards/c01.png" ],
        [ "c02", "/src/assets/img/cards/c02.png" ],
        [ "c03", "/src/assets/img/cards/c03.png" ],
        [ "c04", "/src/assets/img/cards/c04.png" ],
        [ "c05", "/src/assets/img/cards/c05.png" ],
        [ "c06", "/src/assets/img/cards/c06.png" ],
        [ "c07", "/src/assets/img/cards/c07.png" ],
        [ "c08", "/src/assets/img/cards/c08.png" ],
        [ "c09", "/src/assets/img/cards/c09.png" ],
        [ "c10", "/src/assets/img/cards/c10.png" ],
        [ "c11", "/src/assets/img/cards/c11.png" ],
        [ "c12", "/src/assets/img/cards/c12.png" ],
        [ "c13", "/src/assets/img/cards/c13.png" ],
        [ "d01", "/src/assets/img/cards/d01.png" ],
        [ "d02", "/src/assets/img/cards/d02.png" ],
        [ "d03", "/src/assets/img/cards/d03.png" ],
        [ "d04", "/src/assets/img/cards/d04.png" ],
        [ "d05", "/src/assets/img/cards/d05.png" ],
        [ "d06", "/src/assets/img/cards/d06.png" ],
        [ "d07", "/src/assets/img/cards/d07.png" ],
        [ "d08", "/src/assets/img/cards/d08.png" ],
        [ "d09", "/src/assets/img/cards/d09.png" ],
        [ "d10", "/src/assets/img/cards/d10.png" ],
        [ "d11", "/src/assets/img/cards/d11.png" ],
        [ "d12", "/src/assets/img/cards/d12.png" ],
        [ "d13", "/src/assets/img/cards/d13.png" ],
        [ "h01", "/src/assets/img/cards/h01.png" ],
        [ "h02", "/src/assets/img/cards/h02.png" ],
        [ "h03", "/src/assets/img/cards/h03.png" ],
        [ "h04", "/src/assets/img/cards/h04.png" ],
        [ "h05", "/src/assets/img/cards/h05.png" ],
        [ "h06", "/src/assets/img/cards/h06.png" ],
        [ "h07", "/src/assets/img/cards/h07.png" ],
        [ "h08", "/src/assets/img/cards/h08.png" ],
        [ "h09", "/src/assets/img/cards/h09.png" ],
        [ "h10", "/src/assets/img/cards/h10.png" ],
        [ "h11", "/src/assets/img/cards/h11.png" ],
        [ "h12", "/src/assets/img/cards/h12.png" ],
        [ "h13", "/src/assets/img/cards/h13.png" ],
        [ "s01", "/src/assets/img/cards/s01.png" ],
        [ "s02", "/src/assets/img/cards/s02.png" ],
        [ "s03", "/src/assets/img/cards/s03.png" ],
        [ "s04", "/src/assets/img/cards/s04.png" ],
        [ "s05", "/src/assets/img/cards/s05.png" ],
        [ "s06", "/src/assets/img/cards/s06.png" ],
        [ "s07", "/src/assets/img/cards/s07.png" ],
        [ "s08", "/src/assets/img/cards/s08.png" ],
        [ "s09", "/src/assets/img/cards/s09.png" ],
        [ "s10", "/src/assets/img/cards/s10.png" ],
        [ "s11", "/src/assets/img/cards/s11.png" ],
        [ "s12", "/src/assets/img/cards/s12.png" ],
        [ "s13", "/src/assets/img/cards/s13.png" ],
    ]
);

export default cards;